FROM nginx:1.27-alpine

# Copy web application assets
COPY . /usr/share/nginx/html/

# Copy Nginx server configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Remove development / deployment metadata from static web root
RUN rm -rf /usr/share/nginx/html/deploy /usr/share/nginx/html/.git

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
